name: hive_benchmark

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.1.0
  path: ^1.6.4
  random_string: ^1.1.0
  hive: ^0.4.0
  sqflite: ^1.1.6
  shared_preferences: ^0.5.3+4
  fl_chart: ^0.1.6
  moor_ffi: ^0.0.1
  sembast: ^2.1.0+1

flutter:
  uses-material-design: true